name: Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ThiagoAnunciacao/s3cmd-sync-action@v0.2.4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'eu-west-2' # optional: defaults to us-east-1
          S3CMD_SOURCE_DIR: './' # optional: defaults ./ to entire repository
          S3CMD_EXCLUDE: '.git/*' # optional: defaults empty
          S3CMD_EXCLUDE_FROM: '' # optional: defaults empty
          S3CMD_DELETE_REMOVED: 'true' # optional: default true
          S3CMD_ADD_HEADERS: '' # optional: defaults empty
          S3CMD_CF_INVALIDATE: 'true' # optional: default true
          S3CMD_EXTRA_OPTS: '--verbose' # optional: default --verbose
