name: Sync Bucket	name: Publish
on: push	
on:
  push:
    branches:
      - master


jobs:	jobs:
  deploy:	  deploy:
    runs-on: ubuntu-latest	    runs-on: ubuntu-latest
    steps:	    steps:
      - uses: actions/checkout@master	      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master	      - uses: ThiagoAnunciacao/s3cmd-sync-action@v0.2.4
        with:	
        args: --exclude '.git/*'	
        env:	        env:
          SOURCE_DIR: '/Users/sam/Code/personal-projects/cloud-resume-challenge/cloud-resume-frontend'	
          AWS_REGION: 'eu-west-2'	
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}	
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}	          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}